### ISSUE TITLE
Add a @types/threear for typescript support

### ISSUE THREAD

**Issue by arthursp** [google-ar/three.ar.js#10]
It will be usefull to have a typescript support like three.js

**Comment by jsantell** [comment]
My understanding (which could definitely be wrong, haven't used typescript too much) is that the type declarations ([found here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types)) cannot be versioned, and since we're tracking an inherently experimental platform and open to change, the type declarations can easily become out of sync with the library. Does @types handle that? Is that best managed locally in this repo, alongside the source?

**Comment by arthursp** [comment]
Why "is that the type declarations (found here) cannot be versioned" ? 

It can it's a github repo.

Does @types handle that?

Yes it's a github repo

Is that best managed locally in this repo, alongside the source? 

Don't know if it's the best but quite acceptable.

My question is linked to the volunteer to use your script with IONIC.

Ionic have a script that autogenerate definition :https://github.com/ionic-team/ionic-native/blob/master/DEVELOPER.md

maybe the same principle can be applied here, or maybe it will be interesting to create a @ionic-native/threear plugin

**Comment by jsantell** [comment]
Closing this issue, but if someone wanted to submit type definitions, we will check it out. Thanks!

**Comment by cecilemuller** [comment]
Instead of a `@types` package, the definitions could also be in this package (using a "typings" entry in package.json), then users wouldn't require an extra package that risks being out of sync if it's not updated at the same time as this library.

**Comment by jsantell** [comment]
Thanks for the info,, certainly clarifies how to couple the version with the type definition
